### ISSUE TITLE
Can't run test throw PyCharm

### ISSUE THREAD

**Issue by SamGustavson** [stb-tester/stb-tester#476]
Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/rokutester/roku/roku_stbt_testing/scripts/test_basic.py", line 84, in test_text_matching
    press_helper.home()
  File "/home/rokutester/roku/roku_stbt_testing/scripts/helpers/press_helper.py", line 9, in home
    self._press_key('KEY_HOME')
  File "/home/rokutester/roku/roku_stbt_testing/scripts/helpers/press_helper.py", line 27, in _press_key
    stbt.press(key)
  File "/usr/lib/python2.7/dist-packages/stbt/__init__.py", line 104, in press
    return _dut.press(key, interpress_delay_secs)
  File "/usr/lib/stbt/_stbt/core.py", line 767, in press
    self._control.press(key)
AttributeError: 'NoneType' object has no attribute 'press'

**Comment by drothlis** [comment]
I'm guessing that you're trying to run an stb-tester test script without using `stbt run`. This isn't currently supported. See https://github.com/stb-tester/stb-tester/issues/297 for a TODO list if you'd like to contribute.
