### ISSUE TITLE
Portal fails to start up: /var/opt/stbt/etc/id_rsa already exists

### ISSUE THREAD

**Issue by drothlis** [stb-tester/stb-tester#842]
local-server only?

**Comment by drothlis** [comment]
```
❯ instance=daves-house.stb-tester.com ninja deploy-server 
Generating public/private rsa key pair.
/var/opt/stbt/etc/id_rsa already exists.
Overwrite (y/n)? Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/stb-tester-service/http_service/service.py", line 2035, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/stb-tester-service/http_service/service.py", line 430, in main
    committer = Committer(
  File "/usr/lib/stb-tester-service/http_service/git.py", line 938, in __init__
    _setup_commit_signing(portal_name, signingkey)
  File "/usr/lib/stb-tester-service/http_service/git.py", line 847, in _setup_commit_signing
    subprocess.check_call([
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh-keygen', '-t', 'rsa', '-b', '4096', '-N', '', '-f', '/var/opt/stbt/etc/id_rsa', '-C', 'noreply@daves-house.stb-tester.com']' returned non-zero exit status 1.
```

**Comment by drothlis** [comment]
Even more weirdly, `_build/local-server/etc/id_rsa` is an empty folder.

**Comment by drothlis** [comment]
I removed `_build/local-server/etc/id_rsa` and daves-house starts up now.
